#! /bin/sh

# Script for debugging when the election record
# is in $1 or ../1.91/sample if $1 is not set.

path=${1:-../1.91/sample}

./ju <<EOF
using ElectionGuardVerifier1X
validate("$path", "vr.json")
EOF
